#!/usr/bin/env bash
# Script that transfers a file from our client to a server

# Check if less than 4 parameters are passed
if [ "$#" -lt 4 ]; then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

FILE_PATH="$1"
SERVER_IP="$2"
USERNAME="$3"
SSH_KEY_PATH="$4"

# Transfer the file using scp
if scp -i "$SSH_KEY_PATH" -o StrictHostKeyChecking=no -- "$FILE_PATH" "$USERNAME@$SERVER_IP:~/"; then
    echo "File transferred successfully to $USERNAME@$SERVER_IP:~/"
else
    echo "Failed to transfer the file."
    exit 1
fi