#!/usr/bin/env bash
# Bash script that stops 4-to_infinity_and_beyond process.

id=$(pgrep -f "bash ./4-to_infinity_and_beyond")

if [[ -n $id ]]
then
    pkill -TERM -f "bash ./4-to_infinity_and_beyond"
fi
