#!/usr/bin/env bash
# This script is displaying "Best School" 9 times and 1 Hi

i=0

while [ $i -le 9 ]
do
    echo "Best School"
    if [ "$i" = 8 ]
    then
        echo "Hi"
    fi

    ((i++))
done
